### ISSUE TITLE
Timeout expired. AGILENT TECHNOLOGIES,DSO-X 2004A

### ISSUE THREAD

**Issue by fc469** [pyvisa/pyvisa#427]
Hi,
when I start the script below (Simple Example from the documentation).

```Pyhon
import visa
rm = visa.ResourceManager()

my_instrument = rm.open_resource('USB0::0x0957::0x179A::MY52161403::INSTR')
my_instrument.write_termination = '\n'
my_instrument.read_termination ='\n'

my_instrument.write('*IDN?')
while True:
    print(my_instrument.read_bytes(1))
```
 I get the answer in single characters: b'A', b'G...,b'\n'. The last character is '\n', which is set for the read_termination, but I still get VI_ERROR_TMO (-1073807339), Timeout.... If I try just 
```Python
>>> my_instrument.write('*IDN?') 
>>> my_instrument.read()`
```
I get the answer 'AGILENT TECHNOLOGIES,DSO-X 2004A,MY52161403,02.35.2013061800', without the new line character '/n' at the end. Why is '/n' in the byte-wise read but not here? I think I cannot continue to actually controlling the device before solving this. 

Thank you
Filip

**Comment by MatthieuDartiailh** [comment]
In your while loop, you read a character at a time but do not stop after seeing the termination character `\n`. As a consequence you attempt to read again after the instrument is done and get a timeout because it cannot answer.
In the second case, PyVISA is simply automatically stripping the termination character that is most of the time irrelevant to the message. You can use `read_raw` to get the message as read from the instrument (in bytes and with the termination character(s) left in. 
This should answer your questions feel free to re-open if it is not the case.
