### ISSUE TITLE
 Pyinstaller to pack the pyvisa-py 

### ISSUE THREAD

**Issue by universeviva** [pyvisa/pyvisa#784]
I have a question about pyinstaller 

i use the Pyinstaller to pack the pyvisa-py in order to get a executable program in ubuntu.

i exe the programer that can detect network instrument but not detect usb instrument.

system environment: ubuntu 

pack command :pyinstaller --distpath /opt/ate-conn-uni-standard --name conn-stand --collect-all=sanic --hidden-import=pyvisa_py --hidden-import=pyusb  -F main.py

I look forward to your reply. Thank you very much

**Comment by LongnoseRob** [comment]
Have you read the docu on pyinstaller esp [the troubleshooting guide](https://pyinstaller.org/en/stable/when-things-go-wrong.html#finding-out-what-went-wrong)?
Would it be possible to share the logfiles?

I assume usb instruments are not detected due to missing pyusb or its lower-lvel dependencies..
Could also be a linux user-rights issue..

**Comment by universeviva** [comment]
i understand thank you

**Comment by universeviva** [comment]
thank you i see
