### ISSUE TITLE
Could not open VISA library

### ISSUE THREAD

**Issue by bucasper** [pyvisa/pyvisa#79]
Hi,

I got a problem by using VISA library on Win8.1 x64 system. below is what I got when the sequence is: rm = visa.ResourceManager('C:\Windows\system32\visa32.dll')
# Please help.

Machine Details:
   Platform ID:    Windows-8-6.2.9200
   Processor:      Intel64 Family 6 Model 61 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Python33\python.exe
   Version:        3.3.2
   Compiler:       MSC v.1600 32 bit (Intel)
   Bits:           32bit
   Build:          May 16 2013 00:03:43 (#v3.3.2:d047928ae3f6)
   Unicode:        UCS4

VISA:
   PyVISA Version: 1.6.dev0

   #1: C:\Windows\system32\visa32.dll
      found by: auto
      bitness: 32
   #2: C:\Windows\system32\visa32.dll
      found by: auto
      bitness: 32

Traceback (most recent call last):
  File "C:\Users\cyen\workspace\ForcePad_EVT\FuncGen - bk.py", line 6, in <module>
    rm = visa.ResourceManager('C:\Windows\system32\visa32.dll')
  File "C:\Python33\Lib\site-packages\pyvisa\highlevel.py", line 1419, in **new**
    visa_library = open_visa_library(visa_library)
  File "C:\Python33\Lib\site-packages\pyvisa\highlevel.py", line 1398, in open_visa_library
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:
# object() takes no parameters

**Comment by hanwlin** [comment]
Hello, I am having a similar issue:

The error message:
k1@k1-HP-350-G2 ~/Desktop $ python script.py
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    NA = NA_AgilentN5245A.NA_AgilentN5245A(NA_IPaddress)
  File "/home/k1/Desktop/NA_AgilentN5245A.py", line 48, in __init__
    self.connect(ip_address, reset, use_HiSLIP=use_HiSLIP)
  File "/home/k1/Desktop/NA_AgilentN5245A.py", line 56, in connect
    rm=visa.ResourceManager('')
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/highlevel.py", line 1488, in __new__
    visa_library = open_visa_library(visa_library)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/highlevel.py", line 1460, in open_visa_library
    return cls(argument)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/highlevel.py", line 96, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:

I am calling ResourceManager() with no argument since I am not sure what directory to pass to it.

My system information:
k1@k1-HP-350-G2 ~/Desktop $ cat /proc/version
Linux version 3.13.0-37-generic (buildd@kapok) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014

Any help would be appreciated! Thanks.

**Comment by hgrecco** [comment]
Do you have VISA installed?

**Comment by hanwlin** [comment]
Thanks, I don't:
k1@k1-HP-350-G2 ~ $ python -m visa info
Machine Details:
   Platform ID:    Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /usr/bin/python
   Version:        2.7.6
   Compiler:       GCC 4.8.2
   Bits:           64bit
   Build:          Mar 22 2014 22:59:56 (#default)
   Unicode:        UCS4

PyVISA Version: 1.9.dev0

Backends:
   ni:
      Version: 1.9.dev0 (bundled with PyVISA)
      Binary library: Not found


I followed the installation instructions found here:
http://www.ni.com/download/ni-visa-5.4/4234/en/

Even though the installation appeared to complete successfully, I still don't seem to have any NI VISA binary library. A folder is created at: /usr/local/natinst/share/etc/ but it is empty except for a text file "share.dir".

I understand that this is no longer a PyVISA issue, but I was wondering if you have any tips regarding the NI VISA Linux installation?

**Comment by hgrecco** [comment]
The usage of PyVISA requires NI-VISA. If you are not able to install it, you can try the py backend which is a Python implementation of VISA. Take a look at http://pyvisa-py.readthedocs.org/en/latest/

**Comment by bucasper** [comment]
Hi Hernan,

Got it and thanks for your sharing.

Best Regards,
Casper

**Comment by 986123871** [comment]
I face the same problem like Hanwlin，Did you solve it？may you share the solution？please~~~
